language: php

sudo: false

matrix:
  include:
    - php: 5.5
    - php: 5.6
#    - php: 5.6
#      env: SYMFONY_VERSION=2.8.*
#    - php: 5.6
#      env: SYMFONY_VERSION=3.0.*
#    - php: 5.6
#      env: SYMFONY_VERSION=3.1.*
    - php: 7.0
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true

before_install: composer selfupdate

install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}"; fi;
  - composer install

before_script: mkdir -p build/logs

script: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script: vendor/bin/coveralls -v
